export const LOGIN = "LOGIN";

export const REQUEST_AUTHENTICATION = "REQUEST_AUTHENTICATION";
export const AUTHENTICATION_REQUEST_SUCCESS = "AUTHENTICATION_REQUEST_SUCCESS";
export const AUTHENTICATION_REQUEST_FAIL = "AUTHENTICATION_REQUEST_FAIL ";

export const REQUEST_LIST_FILES = "REQUEST_LIST_FILES";
export const REQUEST_FILES_SUCCESS = "REQUEST_FILES_SUCCESS";
export const REQUEST_FILES_FAIL = "REQUEST_FILES_FAIL";

export const LOGOUT = "LOGOUT";
